### ISSUE TITLE
Get-PnPSiteTemplate : The underlying connection was closed: A connection that was expected to be kept alive was closed by the  server

### ISSUE THREAD

**Issue by iloving** [pnp/pnpframework#351] opened 2021-05-25 19:51 UTC
When I try to download a site template as described here: https://pnp.github.io/powershell/cmdlets/Get-PnPSiteTemplate.html?q=get-pnpsitetemplate

It does some stuff and then eventually aborts with the error "Get-PnPSiteTemplate : The underlying connection was closed: A connection that was expected to be kept alive was closed by the  server"

I was able to work around it by explicitly saving the connection to a variable with Connect-PnPOnline, but there was no mention in the documentation that this would even be necessary.

**Comment by patrikhellgren** [comment] 2021-05-26 08:04
@iloving This seems like it could be related to #292. Since that is a very intermittent issue can you verify that it really always works when storing the connection in a variable. For me it can take thousands of calls until I see the error so you may not see it for a smaller template.

**Comment by iloving** [comment] 2021-05-26 13:27
I think you may be right.  I ran into the problem again yesterday when when I ran the command with -PersistBrandingFiles, but I'm trying again and now it's not failing.

**Comment by jansenbe** [comment] 2021-06-07 07:20
closing as duplicate of #292

**Closed by jansenbe** 2021-06-07 07:20 UTC
