### ISSUE TITLE
SiteSearch issue with large IndexDocId values (double vs long)

### ISSUE THREAD

**Issue by marcoscheel** [pnp/pnpframework#174] opened 2021-02-12 16:53 UTC
I'm running an Azure Function to loop trough all sites in a SharePoint tenant. I'm using the extension method:

SiteSearch

I revisited my code recently in a larger customer installation and I found that my search got canceled after a long period (23 minutes). I checked the code and found a problem in data typ conversion. The values of the search result contain a number called "IndexDocId". The "SiteEntity" class is representing the field as a double. But with larger values the filter introduced in the SearchSite code will turns into an endless loop.

In my opinion the code must be changed from:

```C#
public double IndexDocId
        {
            get;
            set;
        }
```
to
```C#
public long IndexDocId
        {
            get;
            set;
        }
```

https://github.com/pnp/pnpframework/blob/155d16ceffe6246a8b3f6382f5e4cff600406762/src/lib/PnP.Framework/Entities/SiteEntity.cs#L58

I've modified my running code and it is working for me as expected. Maybe someone can have a look and see if this is indeed a bug and needs to change.

This is the problematic code:
https://github.com/pnp/pnpframework/blob/5e0265eed082abc80e3d2b4f16fe7d25eb763f61/src/lib/PnP.Framework/Extensions/WebExtensions.cs#L617

From this documentation it looks like the docid aka indexdocid should be a INt64:
https://docs.microsoft.com/en-us/sharepoint/dev/general-development/pagination-for-large-result-sets
`            <d:ValueType>Edm.Int64</d:ValueType>`

Checking MS C# docs it looks like an int64 will translate to a long:
https://docs.microsoft.com/en-us/dotnet/api/system.int64?view=net-5.0

**Comment by jansenbe** [comment] 2021-02-16 18:51
Nice catch @marcoscheel ! I've heard about this endless search loop in other situations but we never did pinpoint the root cause, this might be it.

**Comment by jansenbe** [comment] 2021-02-16 18:55
I've just made the change, will be part of the next nightly. Closing this one now, don't hesitate to reach out if things might still not work as expected.

**Closed by jansenbe** 2021-02-16 18:55 UTC
Labels: area: other 🎁, bug
